name: BlockBreakingIsRandom
version: '${project.version}'
main: me.dolphy69.blockbreakingisrandom.BlockBreakingIsRandom
api-version: 1.19
authors: [ Dolphy69 ]
description: Block Breaking Is Random
commands:
  startBBIR:
    description: Start/Stop the game
    usage: /<command>
    default: op
  rerollBBIR:
    description: Rerandomize everything
    usage: /<command>
    default: op
